---

- name: Template Python script before zipping it up
  template:
    src: lambda-handler.py
    dest: "/tmp/xvt-{{ vpc_name }}-cloudfront-ips.py"
  connection: local

  # TODO: Use archive module when we switch to Ansible 2.3
- name: Compress Python file so it can uploaded
  command: "zip -c xvt-{{ vpc_name }}-cloudfront-ips.zip xvt-{{ vpc_name }}-cloudfront-ips.py"
  args:
    chdir: /tmp
  connection: local

- name: Create CloudFront IP managed Lambda
  lambda:
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    name: "xvt-{{ vpc_name }}-cloudfront-ips"
    state: present
    zip_file: "/tmp/xvt-{{ vpc_name }}-cloudfront-ips.zip"
    runtime: python2.7
    timeout: 30
    role: "xvt-{{ vpc_name }}-cloudfront-ips"
    handler: "xvt-{{ vpc_name }}-cloudfront-ips.lambda_handler"

- name: Clean up files after they've been used
  file:
    path: "{{item}}"
    state: absent
  with_items:
    - "/tmp/xvt-{{ vpc_name }}-cloudfront-ips.zip"
    - "/tmp/xvt-{{ vpc_name }}-cloudfront-ips.py"
  connection: local
