---

- name: List function versions
  lambda_facts:
    region: "{{ region }}"
    profile: "{{ profile|default(omit) }}"
    query: all
    name: "xvt-{{ vpc_name }}-cloudfront-ips"
  register: register_discovered_lambda

- set_fact:
    fact_lambda_name: "xvt-{{ vpc_name }}-cloudfront-ips"

- set_fact:
    fact_lambda_arn: "{{register_discovered_lambda.ansible_facts.lambda_facts.function[fact_lambda_name].function_arn}}"

- name: Subscribe our Lambda to the AWS provided IP SNS topic
  command: "aws --profile {{profile}} sns subscribe --topic-arn {{aws_ip_space_sns_arn}} --protocol lambda --notification-endpoint {{fact_lambda_arn}}"
  environment:
    # We have to switch regions because the SNS topic we're subbing to
    # was created in us-east-1, so we have to create the subscription there.
    AWS_DEFAULT_REGION: us-east-1

  # We have to use the above command as the below module struggles with this simple concept.
  # Perhaps someone is willing to invest more time into diagnosing the problem and finding a solution,
  # But enough time has been spent on this already.

  # sns_topic:
  #   name: arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged
  #   display_name: CloudFront IP change notification
  #   state: present
  #   purge_subscriptions: False
  #   subscriptions:
  #     - endpoint: "{{register_discovered_lambda.ansible_facts.lambda_facts.function[fact_lambda_name].function_arn}}"
  #       protocol: lambda
  # environment:
  #   AWS_DEFAULT_REGION: us-east-1
